#!/bin/bash
#
#       /etc/init.d/sqs-listener
#
#       This SQS Listener polls amazon aws for provisioning commands.
#

# Source function library.
. /etc/init.d/functions
. /etc/bang/.activate-BANG

prog="bang-dispatcher"
OPTIONS="~/.sqslistener"
PIDFILE="/var/lock/subsys/sqs-listener"

start() {
        echo -n "Starting sqs-listener: "
        daemon $prog $OPTIONS
        RET=$?
        touch $PIDFILE
        return $RET
}

stop() {
        echo -n "Shutting down sqs-listener: "
        killproc $prog
        RET=$?
        rm -f $PIDFILE
        return $RET
}

check_status() {
    status -p $PIDFILE $prog
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        check_status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: sqs-listener {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
