#!/bin/bash
#
#       /etc/init.d/sqs-listener
#
#       This SQS Listener polls amazon aws for provisioning commands.
#

# Source function library.
. /etc/init.d/functions

# Default options
CONFIG_PATH="~/.sqslistener"
PIDFILE="/var/lock/subsys/sqs-listener"
BANG_DISPATCHER="bang-dispatcher" # Uses system executable unless overriden.

# User-specified variables
. /etc/default/bang-dispatcher

if [ -z $BANG_DISPATCHER ]; then
        >&2 echo "Error: BANG_DISPATCHER variable cannot be empty."
        exit 1
fi

if [ -z $HOME ]; then
        export HOME='/root'
fi

start() {
        echo -n "Starting sqs-listener: "
        daemon $BANG_DISPATCHER $CONFIG_PATH
        RET=$?
        touch $PIDFILE
        return $RET
}

stop() {
        echo -n "Shutting down sqs-listener: "
        killproc $BANG_DISPATCHER
        RET=$?
        rm -f $PIDFILE
        return $RET
}

check_status() {
    status -p $PIDFILE $BANG_DISPATCHER
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        check_status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: sqs-listener {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?