#!/bin/bash
#
#       /etc/init.d/sqs-listener
#
#       This SQS Listener polls amazon aws for provisioning commands.
#

# Source function library.
. /etc/init.d/functions

# Default options
CONFIG_PATH="~/.sqslistener"
PIDFILE="/var/lock/subsys/sqs-listener"
BANG_DISPATCHER="bang-dispatcher" # Uses system executable unless overriden.

# User-specified variables
. /etc/default/bang-dispatcher

if [ -z $BANG_DISPATCHER ]; then
        >&2 echo "Error: BANG_DISPATCHER variable cannot be empty."
        exit 1
fi

start() {
    if [ ! -e $PIDFILE ]; then
		echo -n "Starting sqs-listener: "
      	daemon $BANG_DISPATCHER $CONFIG_PATH -p $PIDFILE &>/dev/null &
       	RET=$?
       	echo $! > $PIDFILE
       	return $RET
	else
		if [ -d /proc/`cat $PIDFILE` ]; then
			echo "Sqs-listener is already running."
		else
			echo "A stale pid file exists, deleting..."
			rm -f $PIDFILE
			start
		fi
	fi
}

stop() {
    echo -n "Shutting down sqs-listener: "
    killproc -p $PIDFILE $BANG_DISPATCHER
    RET=$?
    rm -f $PIDFILE
    return $RET
}

check_status() {
    status -p $PIDFILE $BANG_DISPATCHER
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        check_status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: sqs-listener {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?