#!/bin/bash
#
#       /etc/init.d/sqs-listener
#
#       This SQS Listener polls amazon aws for provisioning commands.
#

# Source function library.
. /etc/init.d/functions

# Default options
BANG_DISPATCHER="bang-dispatcher" # Uses system executable unless overriden.

# User-specified variables
. /etc/default/bang-dispatcher

CONFIG_PATH="~$RUN_AS_USER/.sqslistener"

if [ -z RUN_AS_USER ]; then
	RUN_AS_USER='root'
fi

if [ -z $BANG_DISPATCHER ]; then
        >&2 echo "Error: BANG_DISPATCHER variable cannot be empty."
        exit 1
fi

start() {
    pgrep $BANG_DISPATCHER &> /dev/null
	running=$?
	if [ ! $running ]; then
		echo -n "Starting sqs-listener: "
      	daemon $BANG_DISPATCHER $CONFIG_PATH --user $RUN_AS_USER &> /home/bang-dispatcher/sqslistener/logs/debug.log &
       	return $?
	else
		echo "Sqs-listener is already running."
		return 0
	fi
}

stop() {

    echo -n "Shutting down sqs-listener: "
    killproc $BANG_DISPATCHER
    return $?
}

check_status() {
    status $BANG_DISPATCHER
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        check_status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: sqs-listener {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?